dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 3.0
script:
  - dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
deploy:
  provider: releases
  api_key: "${GithubToken}"
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true